version: '3.8'

services:
  virtualinfluencer:
    build:
      context: .
      dockerfile: Dockerfile.new
    container_name: virtualinfluencer
    restart: unless-stopped
    privileged: true
    ports:
      - "8000:8000"  # FastAPI
      - "5037:5037"  # ADB
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./accounts:/app/accounts
      - adb-keys:/root/.android
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - ADB_DEVICE_IP=192.168.50.202
      - ADB_DEVICE_PORT=42356
      - NOCODB_BASE_URL=${NOCODB_BASE_URL}
      - NOCODB_TOKEN=${NOCODB_TOKEN}
      - NOCODB_PROJECT_ID=${NOCODB_PROJECT_ID}
      - NOCODB_HISTORY_FILTERS_TABLE_ID=${NOCODB_HISTORY_FILTERS_TABLE_ID}
      - NOCODB_HISTORY_FILTERS_VIEW_ID=${NOCODB_HISTORY_FILTERS_VIEW_ID}
      - NOCODB_INTERACTED_USERS_TABLE_ID=${NOCODB_INTERACTED_USERS_TABLE_ID}
      - NOCODB_INTERACTED_USERS_VIEW_ID=${NOCODB_INTERACTED_USERS_VIEW_ID}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allow access to host network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  adb-keys:
