version: '3.8'

services:
  virtualinfluencer:
    build:
      context: .
      dockerfile: Dockerfile
    image: virtualinfluencer:latest
    container_name: virtualinfluencer
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    volumes:
      - ./logs:/app/logs
      - ./accounts:/app/accounts
      - ./data:/app/data
      - ${USERPROFILE}/.android:/root/.android  # Share ADB keys for Windows
    environment:
      - HOME=/root  # Set HOME explicitly
      - ADB_SERVER_SOCKET=tcp:5037
      - NOCODB_BASE_URL=${NOCODB_BASE_URL}
      - NOCODB_TOKEN=${NOCODB_TOKEN}
      - NOCODB_PROJECT_ID=${NOCODB_PROJECT_ID}
      - NOCODB_HISTORY_FILTERS_TABLE_ID=${NOCODB_HISTORY_FILTERS_TABLE_ID}
      - NOCODB_HISTORY_FILTERS_VIEW_ID=${NOCODB_HISTORY_FILTERS_VIEW_ID}
      - NOCODB_INTERACTED_USERS_TABLE_ID=${NOCODB_INTERACTED_USERS_TABLE_ID}
      - NOCODB_INTERACTED_USERS_VIEW_ID=${NOCODB_INTERACTED_USERS_VIEW_ID}
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    privileged: true  # Required for USB device access
